name: CMake Windows Build

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Build without Release'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false
        
env:
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: 'lua zlib rapidjson curl'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
          vcpkgTriplet: 'x64-windows-static'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build-windows

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build-windows
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE='${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake' -DVCPKG_TARGET_TRIPLET=x64-windows-static

      - name: Build
        working-directory: ${{github.workspace}}/build-windows
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
            name: BeamMP Windows
            path: ${{github.workspace}}/build-windows/Release/BeamMP-Server.exe
